title: "Konferenz: KommunikationsFluten"
base_url: /data # http://jekyllrb.com/docs/github-pages/#project-page-url-structure
defaults:
  - scope: {path: ""}
    values:
      layout: "page"

registration_php_url: "/register.php"
